// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Bogner Chess
// Additional permission under GPL-3.0 section 7: see LICENSE-APP-STORE-PERMISSION.md.

import 'dart:io';

import 'package:bogner_chess/config/env.dart';
import 'package:bogner_chess/core/auth/auth_state.dart';
import 'package:bogner_chess/core/consent/consent_state.dart';
import 'package:bogner_chess/core/ui/widgets/draft_badge.dart';
import 'package:bogner_chess/features/consent/ui/ai_consent_screen.dart';
import 'package:bogner_chess/router.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';

import '../../helpers/account_harness.dart';
import '../../helpers/pump_app.dart';

void main() {
  /// Opens the screen the way the submit flow does and returns its result.
  Future<Future<bool?>> open(WidgetTester tester) async {
    final result = routerOf(tester).push<bool>(AppRoutes.consentAi);
    await tester.pumpAndSettle();
    expect(find.byType(AiConsentScreen), findsOneWidget);
    return result;
  }

  testWidgets('names the provider, what is sent and what is not', (
    tester,
  ) async {
    final h = AccountHarness(scenarios: {'MyAiConsent': 'required'})
      ..serveLegalDocumentsByLanguage();
    await pumpApp(tester, overrides: h.overrides);
    await open(tester);

    expect(find.text('AI analysis of your games'), findsOneWidget);
    expect(
      find.textContaining(
        'Analysis comments are generated by Example AI Provider.',
        findRichText: true,
      ),
      findsOneWidget,
    );
    // The backend's Markdown, rendered.
    expect(
      find.textContaining('No account data is sent', findRichText: true),
      findsOneWidget,
    );
    expect(find.text('What is sent to the AI provider'), findsOneWidget);
    expect(find.text('The moves of the game'), findsOneWidget);
    expect(find.text('What is never sent'), findsOneWidget);
    expect(find.text('Your e-mail address'), findsOneWidget);
    expect(find.textContaining('Version 1'), findsOneWidget);
    // A placeholder text, on a build that is not prod.
    expect(find.byType(DraftBadge), findsOneWidget);
    expect(find.text('Agree and continue'), findsOneWidget);
    expect(find.text('Not now'), findsOneWidget);

    expect(h.api.requestsOf('LegalDocument').single.variables, {
      'key': 'AI_CONSENT',
      'language': 'en',
    });
  });

  testWidgets('agreeing records the version that was shown and pops true', (
    tester,
  ) async {
    final h = AccountHarness(scenarios: {'MyAiConsent': 'required'});
    await pumpApp(tester, overrides: h.overrides);
    final result = await open(tester);

    await tester.tap(find.byKey(AiConsentScreen.agreeKey));
    await tester.pumpAndSettle();

    expect(await result, isTrue);
    expect(find.byType(AiConsentScreen), findsNothing);
    expect(h.api.requestsOf('RecordAiConsent').single.variables['input'], {
      'version': 1,
    });
    expect(h.analytics.names, ['consent_ai_accepted']);
    expect(
      containerOf(tester).read(aiConsentStatusProvider).value?.required,
      isFalse,
    );
  });

  testWidgets('"Not now" and the close button pop false and record nothing', (
    tester,
  ) async {
    final h = AccountHarness(scenarios: {'MyAiConsent': 'required'});
    await pumpApp(tester, overrides: h.overrides);

    var result = await open(tester);
    await tester.tap(find.byKey(AiConsentScreen.notNowKey));
    await tester.pumpAndSettle();
    expect(await result, isFalse);

    result = await open(tester);
    await tester.tap(find.byTooltip('Close'));
    await tester.pumpAndSettle();
    expect(await result, isFalse);

    expect(h.api.requestsOf('RecordAiConsent'), isEmpty);
    expect(h.analytics.events, isEmpty);
  });

  testWidgets('offline: no consent, an explanation and a retry', (
    tester,
  ) async {
    final h = AccountHarness(scenarios: {'MyAiConsent': 'required'});
    h.api.fail('LegalDocument', const SocketException('offline'));
    await pumpApp(tester, overrides: h.overrides);
    await open(tester);

    expect(find.text('You are offline'), findsOneWidget);
    expect(find.textContaining('only be given online'), findsOneWidget);
    expect(find.byKey(AiConsentScreen.agreeKey), findsNothing);

    h.api.use('LegalDocument', 'default');
    await tester.tap(find.text('Try again'));
    await tester.pumpAndSettle();
    expect(find.byKey(AiConsentScreen.agreeKey), findsOneWidget);
  });

  testWidgets('a consent that cannot be saved keeps the screen open', (
    tester,
  ) async {
    final h = AccountHarness(scenarios: {'MyAiConsent': 'required'});
    h.api.fail('RecordAiConsent', const SocketException('offline'));
    await pumpApp(tester, overrides: h.overrides);
    final result = await open(tester);
    var popped = false;
    unawaitedResult(result, () => popped = true);

    await tester.tap(find.byKey(AiConsentScreen.agreeKey));
    await tester.pumpAndSettle();

    expect(find.textContaining('could not be saved'), findsOneWidget);
    expect(popped, isFalse);
    expect(h.analytics.events, isEmpty);

    h.api.use('RecordAiConsent', 'default');
    await tester.tap(find.byKey(AiConsentScreen.agreeKey));
    await tester.pumpAndSettle();
    expect(await result, isTrue);
  });

  testWidgets('an unreviewed draft is not offered to real users', (
    tester,
  ) async {
    final h = AccountHarness(scenarios: {'MyAiConsent': 'required'});
    await pumpApp(
      tester,
      env: testEnv(envName: 'prod', authMode: AuthMode.real),
      auth: const SignedIn('sub-1'),
      overrides: h.overrides,
    );
    await open(tester);

    expect(find.text('Not available yet'), findsOneWidget);
    expect(find.byKey(AiConsentScreen.agreeKey), findsNothing);
    expect(find.byType(DraftBadge), findsNothing);
  });

  testWidgets('nothing published: not available', (tester) async {
    final h = AccountHarness(
      scenarios: {'MyAiConsent': 'required', 'LegalDocument': 'not_found'},
    );
    await pumpApp(tester, overrides: h.overrides);
    await open(tester);
    expect(find.text('Not available yet'), findsOneWidget);
  });

  testWidgets('opened again after agreeing: read, and withdraw', (
    tester,
  ) async {
    final h = AccountHarness(); // MyAiConsent/default: version 1 accepted
    await pumpApp(tester, overrides: h.overrides);
    await open(tester);

    expect(find.text('You have agreed to this version.'), findsOneWidget);
    expect(find.byKey(AiConsentScreen.agreeKey), findsNothing);

    h.api.use('MyAiConsent', 'required');
    await tester.tap(find.byKey(AiConsentScreen.withdrawKey));
    await tester.pumpAndSettle();

    expect(h.api.requestsOf('RecordConsent').single.variables['input'], {
      'key': 'AI_CONSENT',
      'version': 1,
      'accepted': false,
    });
    // Withdrawn: the screen offers to agree again.
    expect(find.byKey(AiConsentScreen.agreeKey), findsOneWidget);
  });

  testWidgets('a deep link without anything underneath closes to the start', (
    tester,
  ) async {
    final h = AccountHarness(scenarios: {'MyAiConsent': 'required'});
    await pumpApp(tester, overrides: h.overrides);
    routerOf(tester).go(AppRoutes.consentAi);
    await tester.pumpAndSettle();

    await tester.tap(find.byKey(AiConsentScreen.notNowKey));
    await tester.pumpAndSettle();
    expect(locationOf(tester), AppRoutes.initial);
  });

  for (final brightness in Brightness.values) {
    testWidgets('German, text scale 1.3, iPhone SE, ${brightness.name}', (
      tester,
    ) async {
      final h = AccountHarness(scenarios: {'MyAiConsent': 'required'})
        ..serveLegalDocumentsByLanguage();
      await pumpApp(
        tester,
        locale: const Locale('de', 'CH'),
        brightness: brightness,
        textScale: 1.3,
        screen: kIphoneSe,
        overrides: h.overrides,
      );
      await open(tester);

      expect(tester.takeException(), isNull);
      expect(find.text('KI-Analyse deiner Partien'), findsOneWidget);
      expect(find.text('Zustimmen und weiter'), findsOneWidget);
      expect(find.text('Nicht jetzt'), findsOneWidget);
      expect(
        h.api.requestsOf('LegalDocument').single.variables['language'],
        'de',
      );

      // The whole text can be reached, and the buttons stay on screen.
      await tester.drag(
        find.byKey(AiConsentScreen.scrollKey),
        const Offset(0, -2000),
      );
      await tester.pumpAndSettle();
      expect(tester.takeException(), isNull);
      expect(find.text('Was nie gesendet wird'), findsOneWidget);
      expect(
        find.byKey(AiConsentScreen.agreeKey).hitTestable(),
        findsOneWidget,
      );
    });
  }
}

/// Runs [then] when [future] completes, without waiting for it.
void unawaitedResult(Future<Object?> future, void Function() then) {
  // ignore: discarded_futures
  future.whenComplete(then);
}
